export const categoryMap = {
  'android-wear': 'Wear OS',
  'art-and-design': 'Art & Design',
  'auto-and-vehicles': 'Auto & Vehicles',
  beauty: 'Beauty',
  'books-and-reference': 'Books & Reference',
  business: 'Business',
  comics: 'Comics',
  communication: 'Communication',
  dating: 'Dating',
  education: 'Education',
  entertainment: 'Entertainment',
  events: 'Events',
  finance: 'Finance',
  'food-and-drink': 'Food & Drink',
  'health-and-fitness': 'Health & Fitness',
  'house-and-home': 'House & Home',
  'libraries-and-demo': 'Libraries & Demo',
  lifestyle: 'Lifestyle',
  'maps-and-navigation': 'Maps & Navigation',
  medical: 'Medical',
  'music-and-audio': 'Music & Audio',
  'news-and-magazines': 'News & Magazines',
  parenting: 'Parenting',
  personalization: 'Personalization',
  photography: 'Photography',
  productivity: 'Productivity',
  shopping: 'Shopping',
  social: 'Social',
  sports: 'Sports',
  tools: 'Tools',
  'travel-and-local': 'Travel & Local',
  'video-players': 'Video Players & Editors',
  weather: 'Weather',
  unknown: 'Unknown',
  '': 'Unknown',
  null: 'Unknown',
}
