export const criterionMap = {
  advertiserId: 'Advertiser ID',
  androidId: 'Android ID',
  deviceSerialNumber: 'Device Serial Number',
  googleServicesId: 'Google Services Framework ID',
  imei: 'IMEI',
  macAddress: 'MAC Address',
  cellId: 'Cell ID',
  simSerialNumber: 'ICCID/SIM Serial Number',
  imsi: 'IMSI',
  localAreaCode: 'Local Area Code',
  phoneNumber: 'Phone Number',
  age: 'Age',
  audioRecording: 'Audio Recordings',
  calendar: 'Calendar',
  contactBook: 'Contacts',
  country: 'Country',
  ccv: 'CVV',
  dob: 'Date of Birth',
  email: 'Email',
  gender: 'Gender',
  name: 'Name',
  password: 'Password',
  photo: 'Photo',
  physicalAddress: 'Physical Address',
  relationshipStatus: 'Relationship Status',
  sms: 'SMS Messages',
  ssn: 'SSN',
  timezone: 'Timezone',
  username: 'Username',
  video: 'Video',
  webBrowsingLog: 'Web Browsing Log',
  gps: 'GPS (Latitude, Longitude)',
}
